name:  Build and push Django_mongodb image to GCP
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: django_mongodb_image
      PROJECT_ID: civil-accord-396006
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build docker image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Push Docker image to container registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME: latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME: latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest:$GIT_TAG





